
package com.example.demo.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ExampleService", targetNamespace = "http://example.com/demo", wsdlLocation = "file:/Users/administrator/git/spring-boot-soap-client/src/main/resources/wsdl/example.wsdl")
public class ExampleService
    extends Service
{

    private static final URL EXAMPLESERVICE_WSDL_LOCATION;
    private static final WebServiceException EXAMPLESERVICE_EXCEPTION;
    private static final QName EXAMPLESERVICE_QNAME = new QName("http://example.com/demo", "ExampleService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/administrator/git/spring-boot-soap-client/src/main/resources/wsdl/example.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXAMPLESERVICE_WSDL_LOCATION = url;
        EXAMPLESERVICE_EXCEPTION = e;
    }

    public ExampleService() {
        super(__getWsdlLocation(), EXAMPLESERVICE_QNAME);
    }

    public ExampleService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXAMPLESERVICE_QNAME, features);
    }

    public ExampleService(URL wsdlLocation) {
        super(wsdlLocation, EXAMPLESERVICE_QNAME);
    }

    public ExampleService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXAMPLESERVICE_QNAME, features);
    }

    public ExampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExampleService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExampleServicePortType
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleServicePortType getExampleServicePort() {
        return super.getPort(new QName("http://example.com/demo", "ExampleServicePort"), ExampleServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExampleServicePortType
     */
    @WebEndpoint(name = "ExampleServicePort")
    public ExampleServicePortType getExampleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.com/demo", "ExampleServicePort"), ExampleServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXAMPLESERVICE_EXCEPTION!= null) {
            throw EXAMPLESERVICE_EXCEPTION;
        }
        return EXAMPLESERVICE_WSDL_LOCATION;
    }

}
